#!/bin/bash
# Post-process generated Typst file to convert assumption figures to theorem calls

if [ $# -eq 0 ]; then
    echo "Usage: $0 <typst-file>"
    exit 1
fi

TYPST_FILE="$1"

if [ ! -f "$TYPST_FILE" ]; then
    echo "File $TYPST_FILE not found"
    exit 1
fi

echo "Post-processing assumptions in $TYPST_FILE"

# Use sed to replace assumption figures with theorem calls
# This pattern matches the specific structure generated by Quarto
sed -i.bak 's/#figure(\[\
=== \([^<]*\)\
<[^>]*>\
\], caption: figure\.caption(\
position: [^,]*, \
\[\
\([^]]*\)\
\]), \
kind: "quarto-float-ass", \
supplement: "Assumption", \
)\
<\([^>]*\)>/#assumption[*\1*\n\n\2] <\3>/g' "$TYPST_FILE"

echo "Assumption conversion complete. Backup saved as ${TYPST_FILE}.bak"